"""empty message

Revision ID: ff8527feba6b
Revises: fa690eff369a
Create Date: 2025-07-31 12:31:56.730242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff8527feba6b"
down_revision: Union[str, Sequence[str], None] = "fa690eff369a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hierarchy_levels",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("level", sa.INTEGER(), nullable=True),
        sa.Column("prompt", sa.TEXT(), nullable=True),
        sa.Column("analytics_prompt", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "positions", sa.Column("hierarchy_level_id", sa.BIGINT(), nullable=True)
    )
    op.create_foreign_key(
        None, "positions", "hierarchy_levels", ["hierarchy_level_id"], ["id"]
    )
    op.drop_column("positions", "hierarchy_level")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "positions",
        sa.Column("hierarchy_level", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "positions", type_="foreignkey")
    op.drop_column("positions", "hierarchy_level_id")
    op.drop_table("hierarchy_levels")
    # ### end Alembic commands ###
